import { Injectable, signal } from '@angular/core';

export type Lang = 'es' | 'en';

const STORAGE_KEY = 'nexus-lang';

@Injectable({ providedIn: 'root' })
export class TranslateService {
  private translations: Record<string, string> = {};
  readonly currentLang = signal<Lang>(this.detectLang());

  constructor() {
    this.loadTranslations(this.currentLang());
  }

  setLang(lang: Lang): void {
    this.currentLang.set(lang);
    localStorage.setItem(STORAGE_KEY, lang);
    this.loadTranslations(lang);
  }

  toggleLang(): void {
    this.setLang(this.currentLang() === 'es' ? 'en' : 'es');
  }

  t(key: string, params?: Record<string, string | number>): string {
    let text = this.translations[key] ?? key;
    if (params) {
      for (const [k, v] of Object.entries(params)) {
        text = text.replace(`{{${k}}}`, String(v));
      }
    }
    return text;
  }

  private detectLang(): Lang {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored === 'en' || stored === 'es') return stored;
    const browserLang = navigator.language.split('-')[0];
    return browserLang === 'en' ? 'en' : 'es';
  }

  private loadTranslations(lang: Lang): void {
    // Synchronous import from static maps — no async needed
    this.translations = lang === 'en' ? EN : ES;
  }
}

// ─── Spanish translations ───────────────────────────────────────────────────

const ES: Record<string, string> = {
  // ── Nav / Layout ──
  'nav.dashboard': 'Dashboard',
  'nav.contacts': 'Contactos',
  'nav.companies': 'Empresas',
  'nav.deals': 'Deals',
  'nav.activities': 'Actividades',
  'nav.pipeline': 'Pipeline',
  'nav.settings': 'Configuración',

  // ── Topbar / User menu ──
  'topbar.profile': 'Mi perfil',
  'topbar.settings': 'Configuración',
  'topbar.logout': 'Cerrar sesión',
  'role.owner': 'Propietario',
  'role.admin': 'Admin',
  'role.member': 'Miembro',
  'role.sales_rep': 'Ventas',
  'role.viewer': 'Visualizador',

  // ── Auth ──
  'auth.login_title': 'Inicia sesión en tu cuenta',
  'auth.email': 'Email',
  'auth.password': 'Contraseña',
  'auth.login': 'Iniciar sesión',
  'auth.logging_in': 'Iniciando sesión...',
  'auth.no_account': '¿No tienes cuenta?',
  'auth.register_link': 'Regístrate',
  'auth.register_title': 'Crear cuenta',
  'auth.register_subtitle': 'Crea tu organización en NexusCRM',
  'auth.organization': 'Organización',
  'auth.org_name': 'Nombre de la organización',
  'auth.org_slug': 'Slug (identificador único)',
  'auth.org_slug_hint': 'Solo letras, números y guiones. Ej: acme-corp',
  'auth.your_account': 'Tu cuenta',
  'auth.first_name': 'Nombre',
  'auth.last_name': 'Apellido',
  'auth.password_hint': 'Mínimo 8 caracteres, al menos una letra y un número',
  'auth.confirm_password': 'Confirmar contraseña',
  'auth.passwords_mismatch': 'Las contraseñas no coinciden',
  'auth.password_needs_letter': 'Debe contener al menos una letra',
  'auth.password_needs_digit': 'Debe contener al menos un número',
  'auth.password_strength.weak': 'Débil',
  'auth.password_strength.fair': 'Regular',
  'auth.password_strength.good': 'Buena',
  'auth.password_strength.strong': 'Fuerte',
  'auth.password_min_length': 'Mínimo 8 caracteres',
  'auth.password_has_upper': 'Una letra mayúscula',
  'auth.password_has_special': 'Un carácter especial',
  'auth.creating': 'Creando cuenta...',
  'auth.create': 'Crear cuenta',
  'auth.has_account': '¿Ya tienes cuenta?',
  'auth.login_link': 'Inicia sesión',
  'auth.welcome': 'Bienvenido',
  'auth.login_success': 'Has iniciado sesión correctamente',
  'auth.login_error': 'Error al iniciar sesión',
  'auth.login_error_msg': 'Verifica tus credenciales e intenta de nuevo',
  'auth.register_success': 'Cuenta creada',
  'auth.register_welcome': 'Bienvenido a NexusCRM',
  'auth.register_error': 'Error en el registro',
  'auth.register_error_fallback': 'Error al crear la cuenta. Intenta de nuevo.',
  'auth.register_error_generic': 'Verifica los datos',

  // ── Validation ──
  'validation.required': 'Este campo es requerido',
  'validation.email_required': 'El email es requerido',
  'validation.email_invalid': 'Ingresa un email válido',
  'validation.password_required': 'La contraseña es requerida',
  'validation.min_chars': 'Mínimo {{min}} caracteres',
  'validation.pattern_slug': 'Solo letras minúsculas, números y guiones',
  'validation.invalid_field': 'Campo inválido',
  'validation.required_short': 'Requerido',
  'validation.email_invalid_short': 'Email inválido',

  // ── Common actions ──
  'common.save': 'Guardar cambios',
  'common.cancel': 'Cancelar',
  'common.edit': 'Editar',
  'common.delete': 'Eliminar',
  'common.create': 'Crear',
  'common.search': 'Buscar',
  'common.previous': 'Anterior',
  'common.next': 'Siguiente',
  'common.page_of': 'Página {{current}} de {{total}}',
  'common.close': 'Cerrar',
  'common.load_more': 'Cargar más',
  'common.all': 'Todas',
  'common.confirm_action': 'Confirmar acción',
  'common.confirm_default_msg': '¿Estás seguro de que deseas realizar esta acción?',
  'common.no_data': 'No hay datos',
  'common.select': 'Seleccionar',

  // ── Dashboard ──
  'dashboard.title': 'Dashboard',
  'dashboard.subtitle': 'Resumen de tu pipeline y actividad reciente',
  'dashboard.total_contacts': 'Total Contactos',
  'dashboard.total_deals': 'Total Deals',
  'dashboard.pipeline_value': 'Valor del Pipeline',
  'dashboard.conversion_rate': 'Tasa de Conversión',
  'dashboard.won_deals': 'Ganados este mes',
  'dashboard.revenue_chart': 'Ingresos por mes',
  'dashboard.pipeline_chart': 'Pipeline por etapa',
  'dashboard.recent_activity': 'Actividad reciente',
  'dashboard.no_revenue': 'Sin datos de ingresos',
  'dashboard.no_pipeline': 'Sin datos de pipeline',
  'dashboard.no_activity': 'Sin actividad reciente',
  'dashboard.revenue_label': 'Ingresos',
  'dashboard.deals_count': '{{count}} deals',
  'dashboard.activity.call': ' realizó una llamada con ',
  'dashboard.activity.email': ' envió un email a ',
  'dashboard.activity.meeting': ' tuvo una reunión con ',
  'dashboard.activity.note': ' agregó una nota en ',
  'dashboard.activity.task': ' completó una tarea en ',
  'dashboard.activity.deal_created': ' creó el deal ',
  'dashboard.activity.deal_moved': ' movió el deal ',
  'dashboard.activity.contact_created': ' creó el contacto ',
  'dashboard.activity.default': ' interactuó con ',

  // ── Contacts ──
  'contacts.title': 'Contactos',
  'contacts.total': '{{count}} contactos en total',
  'contacts.new': 'Nuevo contacto',
  'contacts.edit': 'Editar contacto',
  'contacts.search': 'Buscar contactos...',
  'contacts.all_sources': 'Todas las fuentes',
  'contacts.col.name': 'Nombre',
  'contacts.col.email': 'Email',
  'contacts.col.company': 'Empresa',
  'contacts.col.source': 'Fuente',
  'contacts.col.assigned': 'Asignado a',
  'contacts.col.created': 'Creado',
  'contacts.col.actions': 'Acciones',
  'contacts.empty_title': 'Sin contactos',
  'contacts.empty_desc': 'Aún no tienes contactos. Crea el primero.',
  'contacts.delete_title': 'Eliminar contacto',
  'contacts.delete_msg': '¿Eliminar a {{name}}? Esta acción no se puede deshacer.',
  'contacts.deleted': 'Contacto eliminado',
  'contacts.created': 'Contacto creado',
  'contacts.updated': 'Contacto actualizado',
  'contacts.no_email': 'Sin email',
  'contacts.detail.info': 'Información',
  'contacts.detail.phone': 'Teléfono',
  'contacts.detail.company': 'Empresa',
  'contacts.detail.source': 'Fuente',
  'contacts.detail.assigned': 'Asignado a',
  'contacts.detail.created': 'Creado',
  'contacts.detail.updated': 'Actualizado',
  'contacts.detail.notes': 'Notas',
  'contacts.detail.delete_msg':
    '¿Estás seguro de que deseas eliminar este contacto? Esta acción no se puede deshacer.',
  'contacts.form.first_name': 'Nombre',
  'contacts.form.last_name': 'Apellido',
  'contacts.form.email': 'Email',
  'contacts.form.phone': 'Teléfono',
  'contacts.form.source': 'Fuente',
  'contacts.form.notes': 'Notas',
  'contacts.form.create': 'Crear contacto',

  // ── Companies ──
  'companies.title': 'Empresas',
  'companies.total': '{{count}} empresas en total',
  'companies.new': 'Nueva empresa',
  'companies.edit': 'Editar empresa',
  'companies.search': 'Buscar empresas...',
  'companies.col.company': 'Empresa',
  'companies.col.industry': 'Industria',
  'companies.col.size': 'Tamaño',
  'companies.col.website': 'Sitio web',
  'companies.col.created': 'Creada',
  'companies.col.actions': 'Acciones',
  'companies.empty_title': 'Sin empresas',
  'companies.empty_desc': 'Aún no tienes empresas registradas.',
  'companies.delete_title': 'Eliminar empresa',
  'companies.delete_msg': '¿Eliminar {{name}}?',
  'companies.deleted': 'Empresa eliminada',
  'companies.created': 'Empresa creada',
  'companies.updated': 'Empresa actualizada',
  'companies.no_domain': 'Sin dominio',
  'companies.detail.info': 'Información',
  'companies.detail.industry': 'Industria',
  'companies.detail.size': 'Tamaño',
  'companies.detail.phone': 'Teléfono',
  'companies.detail.address': 'Dirección',
  'companies.detail.created': 'Creada',
  'companies.detail.notes': 'Notas',
  'companies.detail.contacts': 'Contactos',
  'companies.detail.delete_msg':
    '¿Estás seguro? Esta acción eliminará la empresa y no se puede deshacer.',
  'companies.form.name': 'Nombre',
  'companies.form.domain': 'Dominio',
  'companies.form.website': 'Sitio web',
  'companies.form.industry': 'Industria',
  'companies.form.size': 'Tamaño',
  'companies.form.phone': 'Teléfono',
  'companies.form.address': 'Dirección',
  'companies.form.notes': 'Notas',
  'companies.form.create': 'Crear empresa',
  'companies.form.employees': 'empleados',
  'companies.form.select_size': 'Seleccionar',
  'companies.form.slug_readonly': '(no se puede cambiar)',

  // ── Deals ──
  'deals.title': 'Deals',
  'deals.total': '{{count}} deals en total',
  'deals.new': 'Nuevo deal',
  'deals.edit': 'Editar deal',
  'deals.kanban_view': 'Kanban',
  'deals.list_view': 'Vista lista',
  'deals.all_statuses': 'Todos los estados',
  'deals.status.open': 'Abiertos',
  'deals.status.won': 'Ganados',
  'deals.status.lost': 'Perdidos',
  'deals.col.title': 'Título',
  'deals.col.stage': 'Etapa',
  'deals.col.status': 'Estado',
  'deals.col.value': 'Valor',
  'deals.col.contact': 'Contacto',
  'deals.col.close_date': 'Cierre est.',
  'deals.col.actions': 'Acciones',
  'deals.empty_title': 'Sin deals',
  'deals.empty_desc': 'Crea tu primer deal.',
  'deals.delete_title': 'Eliminar deal',
  'deals.delete_msg': '¿Eliminar {{name}}?',
  'deals.deleted': 'Deal eliminado',
  'deals.created': 'Deal creado',
  'deals.updated': 'Deal actualizado',
  'deals.detail.info': 'Información del deal',
  'deals.detail.value': 'Valor',
  'deals.detail.contact': 'Contacto',
  'deals.detail.company': 'Empresa',
  'deals.detail.assigned': 'Asignado a',
  'deals.detail.close_date': 'Cierre estimado',
  'deals.detail.notes': 'Notas',
  'deals.detail.stage_history': 'Historial de etapas',
  'deals.detail.no_history': 'Sin historial de etapas',
  'deals.detail.current': '(actual)',
  'deals.detail.stage_label': 'Etapa',
  'deals.detail.delete_msg':
    '¿Estás seguro de que deseas eliminar este deal? Esta acción no se puede deshacer.',
  'deals.form.title': 'Título',
  'deals.form.value': 'Valor',
  'deals.form.currency': 'Moneda',
  'deals.form.stage': 'Etapa',
  'deals.form.select_stage': 'Seleccionar etapa...',
  'deals.form.close_date': 'Fecha de cierre estimada',
  'deals.form.notes': 'Notas',
  'deals.form.create': 'Crear deal',

  // ── Kanban ──
  'kanban.title': 'Pipeline Kanban',
  'kanban.subtitle': 'Arrastra los deals entre etapas',
  'kanban.drag_here': 'Arrastra deals aquí',
  'kanban.won': 'Ganado',
  'kanban.lost': 'Perdido',

  // ── Activities ──
  'activities.title': 'Actividades',
  'activities.subtitle': 'Timeline de interacciones',
  'activities.new': 'Nueva actividad',
  'activities.empty_title': 'Sin actividades',
  'activities.empty_desc': 'Registra llamadas, emails, reuniones y notas',
  'activities.mark_complete': 'Marcar completada',
  'activities.delete_title': 'Eliminar actividad',
  'activities.delete_msg': '¿Eliminar esta actividad? Esta acción no se puede deshacer.',
  'activities.created': 'Actividad creada',
  'activities.completed': 'Actividad completada',
  'activities.deleted': 'Actividad eliminada',
  'activities.by': 'por',
  'activities.form.type': 'Tipo',
  'activities.form.subject': 'Asunto',
  'activities.form.body': 'Detalle',
  'activities.form.scheduled': 'Fecha programada',
  'activities.form.create': 'Crear actividad',
  'activities.type.call': 'Llamada',
  'activities.type.email': 'Email',
  'activities.type.meeting': 'Reunión',
  'activities.type.note': 'Nota',
  'activities.type.task': 'Tarea',

  // ── Pipeline ──
  'pipeline.title': 'Pipeline',
  'pipeline.subtitle': 'Gestiona las etapas del pipeline de ventas',
  'pipeline.new_stage': 'Nueva etapa',
  'pipeline.edit_stage': 'Editar etapa',
  'pipeline.drag_hint':
    'Arrastra las etapas para cambiar el orden. Los cambios se guardan automáticamente.',
  'pipeline.order': 'Orden',
  'pipeline.won': 'Ganado',
  'pipeline.lost': 'Perdido',
  'pipeline.mark_won': 'Marcar como Ganado',
  'pipeline.mark_lost': 'Marcar como Perdido',
  'pipeline.form.name': 'Nombre',
  'pipeline.form.color': 'Color',
  'pipeline.form.create': 'Crear etapa',
  'pipeline.delete_title': 'Eliminar etapa',
  'pipeline.delete_msg': '¿Eliminar la etapa {{name}}? Los deals en esta etapa quedarán sin etapa.',
  'pipeline.stage_created': 'Etapa creada',
  'pipeline.stage_updated': 'Etapa actualizada',
  'pipeline.stage_deleted': 'Etapa eliminada',

  // ── Settings ──
  'settings.title': 'Configuración',
  'settings.subtitle': 'Gestiona tu cuenta y organización',
  'settings.profile': 'Mi perfil',
  'settings.organization': 'Organización',
  'settings.users': 'Usuarios',
  'settings.profile.title': 'Mi perfil',
  'settings.profile.subtitle': 'Actualiza tu información personal',
  'settings.profile.first_name': 'Nombre',
  'settings.profile.last_name': 'Apellido',
  'settings.profile.email': 'Email',
  'settings.profile.account_info': 'Información de cuenta',
  'settings.profile.role': 'Rol',
  'settings.profile.member_since': 'Miembro desde',
  'settings.profile.updated': 'Perfil actualizado',
  'settings.org.title': 'Organización',
  'settings.org.subtitle': 'Configura los datos de tu organización',
  'settings.org.name': 'Nombre de la organización',
  'settings.org.slug': 'Slug (identificador)',
  'settings.org.slug_readonly': '(no se puede cambiar)',
  'settings.org.updated': 'Organización actualizada',
  'settings.users.title': 'Usuarios',
  'settings.users.subtitle': 'Gestiona los miembros de tu organización',
  'settings.users.invite': 'Invitar usuario',
  'settings.users.invite_title': 'Invitar usuario',
  'settings.users.col.user': 'Usuario',
  'settings.users.col.role': 'Rol',
  'settings.users.col.status': 'Estado',
  'settings.users.col.actions': 'Acciones',
  'settings.users.you': '(tú)',
  'settings.users.active': 'Activo',
  'settings.users.inactive': 'Inactivo',
  'settings.users.deactivate': 'Desactivar',
  'settings.users.deactivate_title': 'Desactivar usuario',
  'settings.users.deactivate_msg': '¿Desactivar a {{name}}?',
  'settings.users.deactivated': 'Usuario desactivado',
  'settings.users.send_invite': 'Enviar invitación',
  'settings.users.invited': 'Invitación enviada',
  'settings.users.role.member': 'Miembro',
  'settings.users.role.admin': 'Admin',

  // ── Sources ──
  'source.manual': 'Manual',
  'source.import': 'Importado',
  'source.website': 'Sitio web',
  'source.referral': 'Referido',
  'source.social': 'Redes sociales',
  'source.other': 'Otro',

  // ── Deal statuses ──
  'deal_status.open': 'Abierto',
  'deal_status.won': 'Ganado',
  'deal_status.lost': 'Perdido',

  // ── API messages ──
  'api.invalid_credentials': 'Email o contraseña incorrectos',
  'api.account_deactivated': 'La cuenta está desactivada',
  'api.slug_taken': 'El slug de organización ya está en uso',
  'api.email_taken': 'El email ya está registrado',
  'api.user_not_found': 'Usuario no encontrado o desactivado',
  'api.cannot_deactivate_owner': 'No se puede desactivar al propietario',
  'api.cannot_modify_owner': 'No se puede modificar al propietario',
  'api.cannot_deactivate_self': 'No puedes desactivar tu propia cuenta',
  'api.readonly_access': 'Los visualizadores solo tienen acceso de lectura',
  'api.no_permission': 'No tienes permisos para esta acción',
  'api.not_found': 'Recurso no encontrado',

  // ── Errors ──
  'error.generic': 'Ocurrió un error inesperado. Intenta de nuevo.',
  'error.load_contacts': 'Error al cargar contactos',
  'error.delete_contact': 'Error al eliminar contacto',
  'error.save_contact': 'Error al guardar el contacto',
  'error.load_contact': 'Error al cargar el contacto',
  'error.load_companies': 'Error al cargar empresas',
  'error.delete_company': 'Error al eliminar la empresa',
  'error.save_company': 'Error al guardar la empresa',
  'error.load_company': 'Error al cargar la empresa',
  'error.load_deals': 'Error al cargar deals',
  'error.delete_deal': 'Error al eliminar el deal',
  'error.save_deal': 'Error al guardar el deal',
  'error.load_deal': 'Error al cargar el deal',
  'error.move_deal': 'Error al mover el deal',
  'error.load_activities': 'Error al cargar actividades',
  'error.load_more_activities': 'Error al cargar más actividades',
  'error.create_activity': 'Error al crear la actividad',
  'error.complete_activity': 'Error al completar la actividad',
  'error.delete_activity': 'Error al eliminar la actividad',
  'error.load_pipeline': 'Error al cargar el pipeline',
  'error.save_stage': 'Error al guardar la etapa',
  'error.delete_stage': 'Error al eliminar la etapa',
  'error.reorder_stages': 'Error al reordenar las etapas',
  'error.update_profile': 'Error al actualizar el perfil',
  'error.update_org': 'Error al actualizar la organización',
  'error.invite_user': 'Error al enviar la invitación',
  'error.deactivate_user': 'Error al desactivar el usuario',
};

// ─── English translations ───────────────────────────────────────────────────

const EN: Record<string, string> = {
  // ── Nav / Layout ──
  'nav.dashboard': 'Dashboard',
  'nav.contacts': 'Contacts',
  'nav.companies': 'Companies',
  'nav.deals': 'Deals',
  'nav.activities': 'Activities',
  'nav.pipeline': 'Pipeline',
  'nav.settings': 'Settings',

  // ── Topbar / User menu ──
  'topbar.profile': 'My profile',
  'topbar.settings': 'Settings',
  'topbar.logout': 'Log out',
  'role.owner': 'Owner',
  'role.admin': 'Admin',
  'role.member': 'Member',
  'role.sales_rep': 'Sales Rep',
  'role.viewer': 'Viewer',

  // ── Auth ──
  'auth.login_title': 'Sign in to your account',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.login': 'Sign in',
  'auth.logging_in': 'Signing in...',
  'auth.no_account': "Don't have an account?",
  'auth.register_link': 'Sign up',
  'auth.register_title': 'Create account',
  'auth.register_subtitle': 'Create your organization on NexusCRM',
  'auth.organization': 'Organization',
  'auth.org_name': 'Organization name',
  'auth.org_slug': 'Slug (unique identifier)',
  'auth.org_slug_hint': 'Letters, numbers, and hyphens only. E.g.: acme-corp',
  'auth.your_account': 'Your account',
  'auth.first_name': 'First name',
  'auth.last_name': 'Last name',
  'auth.password_hint': 'Minimum 8 characters, at least one letter and one number',
  'auth.confirm_password': 'Confirm password',
  'auth.passwords_mismatch': 'Passwords do not match',
  'auth.password_needs_letter': 'Must contain at least one letter',
  'auth.password_needs_digit': 'Must contain at least one number',
  'auth.password_strength.weak': 'Weak',
  'auth.password_strength.fair': 'Fair',
  'auth.password_strength.good': 'Good',
  'auth.password_strength.strong': 'Strong',
  'auth.password_min_length': 'Minimum 8 characters',
  'auth.password_has_upper': 'One uppercase letter',
  'auth.password_has_special': 'One special character',
  'auth.creating': 'Creating account...',
  'auth.create': 'Create account',
  'auth.has_account': 'Already have an account?',
  'auth.login_link': 'Sign in',
  'auth.welcome': 'Welcome',
  'auth.login_success': 'Signed in successfully',
  'auth.login_error': 'Sign in failed',
  'auth.login_error_msg': 'Check your credentials and try again',
  'auth.register_success': 'Account created',
  'auth.register_welcome': 'Welcome to NexusCRM',
  'auth.register_error': 'Registration error',
  'auth.register_error_fallback': 'Failed to create account. Try again.',
  'auth.register_error_generic': 'Check your data',

  // ── Validation ──
  'validation.required': 'This field is required',
  'validation.email_required': 'Email is required',
  'validation.email_invalid': 'Enter a valid email',
  'validation.password_required': 'Password is required',
  'validation.min_chars': 'Minimum {{min}} characters',
  'validation.pattern_slug': 'Lowercase letters, numbers, and hyphens only',
  'validation.invalid_field': 'Invalid field',
  'validation.required_short': 'Required',
  'validation.email_invalid_short': 'Invalid email',

  // ── Common actions ──
  'common.save': 'Save changes',
  'common.cancel': 'Cancel',
  'common.edit': 'Edit',
  'common.delete': 'Delete',
  'common.create': 'Create',
  'common.search': 'Search',
  'common.previous': 'Previous',
  'common.next': 'Next',
  'common.page_of': 'Page {{current}} of {{total}}',
  'common.close': 'Close',
  'common.load_more': 'Load more',
  'common.all': 'All',
  'common.confirm_action': 'Confirm action',
  'common.confirm_default_msg': 'Are you sure you want to perform this action?',
  'common.no_data': 'No data',
  'common.select': 'Select',

  // ── Dashboard ──
  'dashboard.title': 'Dashboard',
  'dashboard.subtitle': 'Pipeline summary and recent activity',
  'dashboard.total_contacts': 'Total Contacts',
  'dashboard.total_deals': 'Total Deals',
  'dashboard.pipeline_value': 'Pipeline Value',
  'dashboard.conversion_rate': 'Conversion Rate',
  'dashboard.won_deals': 'Won this month',
  'dashboard.revenue_chart': 'Revenue by month',
  'dashboard.pipeline_chart': 'Pipeline by stage',
  'dashboard.recent_activity': 'Recent activity',
  'dashboard.no_revenue': 'No revenue data',
  'dashboard.no_pipeline': 'No pipeline data',
  'dashboard.no_activity': 'No recent activity',
  'dashboard.revenue_label': 'Revenue',
  'dashboard.deals_count': '{{count}} deals',
  'dashboard.activity.call': ' made a call with ',
  'dashboard.activity.email': ' sent an email to ',
  'dashboard.activity.meeting': ' had a meeting with ',
  'dashboard.activity.note': ' added a note on ',
  'dashboard.activity.task': ' completed a task on ',
  'dashboard.activity.deal_created': ' created deal ',
  'dashboard.activity.deal_moved': ' moved deal ',
  'dashboard.activity.contact_created': ' created contact ',
  'dashboard.activity.default': ' interacted with ',

  // ── Contacts ──
  'contacts.title': 'Contacts',
  'contacts.total': '{{count}} contacts total',
  'contacts.new': 'New contact',
  'contacts.edit': 'Edit contact',
  'contacts.search': 'Search contacts...',
  'contacts.all_sources': 'All sources',
  'contacts.col.name': 'Name',
  'contacts.col.email': 'Email',
  'contacts.col.company': 'Company',
  'contacts.col.source': 'Source',
  'contacts.col.assigned': 'Assigned to',
  'contacts.col.created': 'Created',
  'contacts.col.actions': 'Actions',
  'contacts.empty_title': 'No contacts',
  'contacts.empty_desc': "You don't have any contacts yet. Create the first one.",
  'contacts.delete_title': 'Delete contact',
  'contacts.delete_msg': 'Delete {{name}}? This action cannot be undone.',
  'contacts.deleted': 'Contact deleted',
  'contacts.created': 'Contact created',
  'contacts.updated': 'Contact updated',
  'contacts.no_email': 'No email',
  'contacts.detail.info': 'Information',
  'contacts.detail.phone': 'Phone',
  'contacts.detail.company': 'Company',
  'contacts.detail.source': 'Source',
  'contacts.detail.assigned': 'Assigned to',
  'contacts.detail.created': 'Created',
  'contacts.detail.updated': 'Updated',
  'contacts.detail.notes': 'Notes',
  'contacts.detail.delete_msg':
    'Are you sure you want to delete this contact? This action cannot be undone.',
  'contacts.form.first_name': 'First name',
  'contacts.form.last_name': 'Last name',
  'contacts.form.email': 'Email',
  'contacts.form.phone': 'Phone',
  'contacts.form.source': 'Source',
  'contacts.form.notes': 'Notes',
  'contacts.form.create': 'Create contact',

  // ── Companies ──
  'companies.title': 'Companies',
  'companies.total': '{{count}} companies total',
  'companies.new': 'New company',
  'companies.edit': 'Edit company',
  'companies.search': 'Search companies...',
  'companies.col.company': 'Company',
  'companies.col.industry': 'Industry',
  'companies.col.size': 'Size',
  'companies.col.website': 'Website',
  'companies.col.created': 'Created',
  'companies.col.actions': 'Actions',
  'companies.empty_title': 'No companies',
  'companies.empty_desc': "You don't have any companies yet.",
  'companies.delete_title': 'Delete company',
  'companies.delete_msg': 'Delete {{name}}?',
  'companies.deleted': 'Company deleted',
  'companies.created': 'Company created',
  'companies.updated': 'Company updated',
  'companies.no_domain': 'No domain',
  'companies.detail.info': 'Information',
  'companies.detail.industry': 'Industry',
  'companies.detail.size': 'Size',
  'companies.detail.phone': 'Phone',
  'companies.detail.address': 'Address',
  'companies.detail.created': 'Created',
  'companies.detail.notes': 'Notes',
  'companies.detail.contacts': 'Contacts',
  'companies.detail.delete_msg': 'Are you sure? This will delete the company and cannot be undone.',
  'companies.form.name': 'Name',
  'companies.form.domain': 'Domain',
  'companies.form.website': 'Website',
  'companies.form.industry': 'Industry',
  'companies.form.size': 'Size',
  'companies.form.phone': 'Phone',
  'companies.form.address': 'Address',
  'companies.form.notes': 'Notes',
  'companies.form.create': 'Create company',
  'companies.form.employees': 'employees',
  'companies.form.select_size': 'Select',
  'companies.form.slug_readonly': '(cannot be changed)',

  // ── Deals ──
  'deals.title': 'Deals',
  'deals.total': '{{count}} deals total',
  'deals.new': 'New deal',
  'deals.edit': 'Edit deal',
  'deals.kanban_view': 'Kanban',
  'deals.list_view': 'List view',
  'deals.all_statuses': 'All statuses',
  'deals.status.open': 'Open',
  'deals.status.won': 'Won',
  'deals.status.lost': 'Lost',
  'deals.col.title': 'Title',
  'deals.col.stage': 'Stage',
  'deals.col.status': 'Status',
  'deals.col.value': 'Value',
  'deals.col.contact': 'Contact',
  'deals.col.close_date': 'Est. close',
  'deals.col.actions': 'Actions',
  'deals.empty_title': 'No deals',
  'deals.empty_desc': 'Create your first deal.',
  'deals.delete_title': 'Delete deal',
  'deals.delete_msg': 'Delete {{name}}?',
  'deals.deleted': 'Deal deleted',
  'deals.created': 'Deal created',
  'deals.updated': 'Deal updated',
  'deals.detail.info': 'Deal information',
  'deals.detail.value': 'Value',
  'deals.detail.contact': 'Contact',
  'deals.detail.company': 'Company',
  'deals.detail.assigned': 'Assigned to',
  'deals.detail.close_date': 'Estimated close',
  'deals.detail.notes': 'Notes',
  'deals.detail.stage_history': 'Stage history',
  'deals.detail.no_history': 'No stage history',
  'deals.detail.current': '(current)',
  'deals.detail.stage_label': 'Stage',
  'deals.detail.delete_msg':
    'Are you sure you want to delete this deal? This action cannot be undone.',
  'deals.form.title': 'Title',
  'deals.form.value': 'Value',
  'deals.form.currency': 'Currency',
  'deals.form.stage': 'Stage',
  'deals.form.select_stage': 'Select stage...',
  'deals.form.close_date': 'Estimated close date',
  'deals.form.notes': 'Notes',
  'deals.form.create': 'Create deal',

  // ── Kanban ──
  'kanban.title': 'Pipeline Kanban',
  'kanban.subtitle': 'Drag deals between stages',
  'kanban.drag_here': 'Drag deals here',
  'kanban.won': 'Won',
  'kanban.lost': 'Lost',

  // ── Activities ──
  'activities.title': 'Activities',
  'activities.subtitle': 'Interactions timeline',
  'activities.new': 'New activity',
  'activities.empty_title': 'No activities',
  'activities.empty_desc': 'Log calls, emails, meetings, and notes',
  'activities.mark_complete': 'Mark complete',
  'activities.delete_title': 'Delete activity',
  'activities.delete_msg': 'Delete this activity? This action cannot be undone.',
  'activities.created': 'Activity created',
  'activities.completed': 'Activity completed',
  'activities.deleted': 'Activity deleted',
  'activities.by': 'by',
  'activities.form.type': 'Type',
  'activities.form.subject': 'Subject',
  'activities.form.body': 'Details',
  'activities.form.scheduled': 'Scheduled date',
  'activities.form.create': 'Create activity',
  'activities.type.call': 'Call',
  'activities.type.email': 'Email',
  'activities.type.meeting': 'Meeting',
  'activities.type.note': 'Note',
  'activities.type.task': 'Task',

  // ── Pipeline ──
  'pipeline.title': 'Pipeline',
  'pipeline.subtitle': 'Manage your sales pipeline stages',
  'pipeline.new_stage': 'New stage',
  'pipeline.edit_stage': 'Edit stage',
  'pipeline.drag_hint': 'Drag stages to reorder. Changes are saved automatically.',
  'pipeline.order': 'Order',
  'pipeline.won': 'Won',
  'pipeline.lost': 'Lost',
  'pipeline.mark_won': 'Mark as Won',
  'pipeline.mark_lost': 'Mark as Lost',
  'pipeline.form.name': 'Name',
  'pipeline.form.color': 'Color',
  'pipeline.form.create': 'Create stage',
  'pipeline.delete_title': 'Delete stage',
  'pipeline.delete_msg': 'Delete stage {{name}}? Deals in this stage will be unassigned.',
  'pipeline.stage_created': 'Stage created',
  'pipeline.stage_updated': 'Stage updated',
  'pipeline.stage_deleted': 'Stage deleted',

  // ── Settings ──
  'settings.title': 'Settings',
  'settings.subtitle': 'Manage your account and organization',
  'settings.profile': 'My profile',
  'settings.organization': 'Organization',
  'settings.users': 'Users',
  'settings.profile.title': 'My profile',
  'settings.profile.subtitle': 'Update your personal information',
  'settings.profile.first_name': 'First name',
  'settings.profile.last_name': 'Last name',
  'settings.profile.email': 'Email',
  'settings.profile.account_info': 'Account information',
  'settings.profile.role': 'Role',
  'settings.profile.member_since': 'Member since',
  'settings.profile.updated': 'Profile updated',
  'settings.org.title': 'Organization',
  'settings.org.subtitle': 'Configure your organization settings',
  'settings.org.name': 'Organization name',
  'settings.org.slug': 'Slug (identifier)',
  'settings.org.slug_readonly': '(cannot be changed)',
  'settings.org.updated': 'Organization updated',
  'settings.users.title': 'Users',
  'settings.users.subtitle': 'Manage your organization members',
  'settings.users.invite': 'Invite user',
  'settings.users.invite_title': 'Invite user',
  'settings.users.col.user': 'User',
  'settings.users.col.role': 'Role',
  'settings.users.col.status': 'Status',
  'settings.users.col.actions': 'Actions',
  'settings.users.you': '(you)',
  'settings.users.active': 'Active',
  'settings.users.inactive': 'Inactive',
  'settings.users.deactivate': 'Deactivate',
  'settings.users.deactivate_title': 'Deactivate user',
  'settings.users.deactivate_msg': 'Deactivate {{name}}?',
  'settings.users.deactivated': 'User deactivated',
  'settings.users.send_invite': 'Send invitation',
  'settings.users.invited': 'Invitation sent',
  'settings.users.role.member': 'Member',
  'settings.users.role.admin': 'Admin',

  // ── Sources ──
  'source.manual': 'Manual',
  'source.import': 'Imported',
  'source.website': 'Website',
  'source.referral': 'Referral',
  'source.social': 'Social media',
  'source.other': 'Other',

  // ── Deal statuses ──
  'deal_status.open': 'Open',
  'deal_status.won': 'Won',
  'deal_status.lost': 'Lost',

  // ── Errors ──
  // ── API messages ──
  'api.invalid_credentials': 'Invalid email or password',
  'api.account_deactivated': 'Account is deactivated',
  'api.slug_taken': 'Organization slug is already taken',
  'api.email_taken': 'Email is already registered',
  'api.user_not_found': 'User not found or deactivated',
  'api.cannot_deactivate_owner': 'Cannot deactivate the organization owner',
  'api.cannot_modify_owner': 'Cannot modify the organization owner',
  'api.cannot_deactivate_self': 'You cannot deactivate your own account',
  'api.readonly_access': 'Viewers have read-only access',
  'api.no_permission': 'You do not have permission for this action',
  'api.not_found': 'Resource not found',

  'error.generic': 'An unexpected error occurred. Please try again.',
  'error.load_contacts': 'Failed to load contacts',
  'error.delete_contact': 'Failed to delete contact',
  'error.save_contact': 'Failed to save contact',
  'error.load_contact': 'Failed to load contact',
  'error.load_companies': 'Failed to load companies',
  'error.delete_company': 'Failed to delete company',
  'error.save_company': 'Failed to save company',
  'error.load_company': 'Failed to load company',
  'error.load_deals': 'Failed to load deals',
  'error.delete_deal': 'Failed to delete deal',
  'error.save_deal': 'Failed to save deal',
  'error.load_deal': 'Failed to load deal',
  'error.move_deal': 'Failed to move deal',
  'error.load_activities': 'Failed to load activities',
  'error.load_more_activities': 'Failed to load more activities',
  'error.create_activity': 'Failed to create activity',
  'error.complete_activity': 'Failed to complete activity',
  'error.delete_activity': 'Failed to delete activity',
  'error.load_pipeline': 'Failed to load pipeline',
  'error.save_stage': 'Failed to save stage',
  'error.delete_stage': 'Failed to delete stage',
  'error.reorder_stages': 'Failed to reorder stages',
  'error.update_profile': 'Failed to update profile',
  'error.update_org': 'Failed to update organization',
  'error.invite_user': 'Failed to send invitation',
  'error.deactivate_user': 'Failed to deactivate user',
};
